Disable sanitizer detection in v8
The OE sysroot ships no sanitizer/common_interface_defs.h, and our cflags make __has_feature(undefined_behavior_sanitizer) true.

Upstream-Status: Inappropriate [oe specific]

Disable sanitizers

v8/src/sandbox/testing.cc fails to build, due to the included header missing:

| ../../v8/src/sandbox/testing.cc:43:10: fatal error: 'sanitizer/common_interface_defs.h' file not found
|    43 | #include <sanitizer/common_interface_defs.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| 1 error generated.

Better disable defining V8_USE_ANY_SANITIZER to make this
file compile.

Regardless if this is an internally generated header or a system-wide one,
the whole sanitizer build is not necessary.

Disable it at the core, remove defining the macros in v8/src/base/macros.h
that surround the include statement in v8/src/sandbox/testing.cc

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
Upstream-Status: Inappropriate [oe specific]